(load "streams.scm")
(define sum 0)
(define (accum x) (set! sum (+ sum x)) sum)
(display-line sum)
(define seq (mstream-map accum (mstream-enumerate-interval 1 20)))
(display-line sum)
(define y (mstream-filter even? seq))
(display-line sum)
(define z (mstream-filter (lambda (x) (= (remainder x 5) 0)) seq))
(display-line sum)
